
baseURL = "https://hrazhan.github.io/"
languageCode = "en-us"
title = "Razhan Hameed"
theme="archie"
copyright = "© Razhan"
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

linenos = true

ignoreErrors = ["error-missing-instagram-accesstoken"]

[params]
	mode="toggle"
	useCDN=false
	subtitle = "Overcoming my fear of writing."
	# favicon = "https://img.icons8.com/officel/16/000000/chevron-right.png"
	favicon = "favicon.png"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/Hrazhan"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter/RazhanHameed"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/razhan-hameed"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3